config/routes.rb
VotingApp::Application.routes.draw do

  devise_for :users

  resources :articles, except: :index do
    resources :votes
  end

  root 'static_pages#home'

  match '/help',    to: "static_pages#help",    via: 'get'
  match '/about',   to: "static_pages#about",   via: 'get'
  match '/contact', to: "static_pages#contact", via: 'get'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Vote
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :title
	validates_presence_of :body
	validates_presence_of :user

	belongs_to :user

	has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  			 #:recoverable
  			 :rememberable, :trackable, :validatable,
  			 #:confirmable
				:omniauthable
  has_many :articles

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, except: [:show, :index, :home]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected

  def layout_by_controller
  	devise_controller? ? 'devise' : 'application' 	
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	load_and_authorize_resource

	def new
		render 'show_form'
	end

	def create
		article_save
	end

	def destroy
		@article.destroy
		
		respond_to do |format|
      format.js { render :layout => false }
    end

		@article = Article.all
	end

	def edit
		render 'show_form'
	end

	def update
		@article.assign_attributes(article_params)
		article_save
	end

	def show
	end

	private

	def article_save
		if @article.save
			@articles = Article.all
			render 'hide_form'
		else
			render 'show_form'
		end
	end

	def article_params
		params.require(:article).permit(:title, :body)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@articles = Article.all
  end

  def help
  end

  def about  	
  end

  def contact  	
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	load_and_authorize_resource :nested => :article


	def create
		@vote = @article.votes.build
		
		@vote.save!

		respond_to do |format|
      format.js { render :layout => false }
    end
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Voting App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end	
	end

 def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success" # Green
      when :error
        "alert-danger" # Red
      when :alert
        "alert-warning" # Yellow
      when :notice
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_article_form.html.erb
<div class="modal-dialog">
	<div class="modal-header">
      <%= @article.new_record? ? 'New Article' : "Editind : #{@article.title}" %>
    </div>

    <% @article.errors.full_messages.each do |error| %>
    	<li><%= error %></li>
  	<% end %>

  <%= simple_form_for @article, remote: true, class: 'clearfix' do |f| %>
    <div class="modal-body">
      <%= f.input :title %>
      <%= f.input :body %>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/articles/_article_list.html.erb
<% if @articles.empty? %>
	<span class="text-warning">
		There are no articles yet!
	</span>
<% else %>
	<div class="panel panel-default">		
		<div class="panel-heading">
			Articles
		</div>
		<div class="panel-body">
			<ul class="list-group">
				<% @articles.each do |article| %>
					<li class="list-group-item">
						<h2><%= link_to article.title, article_path(article) %></h2>
						
						<%= link_to article_votes_path(article_id: article.id),class: "btn btn-inverse btn-xs btn-hover pull-right", method: :post,  remote: true do %>
							<span class="glyphicon glyphicon-heart"></span>
							<% end %>
							<% if can? :destroy, @article %>
								<%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, remote: true, class: "btn btn-inverse btn-xs btn-hover pull-right" do %>
								<span class="glyphicon glyphicon-remove"></span>
								<% end %>
							<% end %>
						<% if can? :destroy, @article %>
							<%= link_to edit_article_path(article), remote: true, class: "btn btn-inverse btn-xs btn-hover pull-right" do %>
							<span class="glyphicon glyphicon-edit"></span>
							<% end %>
						<% end %></br>
						<%= article.body.truncate(35, separator: ' ') %></br>
						<%= pluralize(article.votes.count, "heart") %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/articles/destroy.js.erb
$('#delete-article').html('<%= j(render partial: 'article_list', locals: ) %>');

app/views/articles/hide_form.js.erb
$('#article_list').html('<%= j(render partial: 'articles/article_list') %>');
$('.modal').modal('hide');

app/views/articles/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1><%= @article.title %></h1>
	</div>
	<div class="panel-body">
		<%= @article.body %>
	</div>
</div>

app/views/articles/show_form.js.erb
m = $('.modal');
m.html('<%= j(render partial: 'article_form', locals: { articles: @articles }) %>');
m.modal('show');

app/views/layouts/_footer.html.erb
<% unless user_signed_in? %>
	<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-lg" %>
<% end %>

<% if user_signed_in? %>
	<p class="navbar-text">Signed in as <%= current_user.email %>
<% end %>
<footer class="footer">
	<div class="container">
		<small>
			A simple article voting app by Alex.
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
			</ul>
		</nav>
		<%= link_to image_tag("voted_today.gif", alt: "Voting app"), root_path %>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar navbar-fixed-top navbar-default">
	<div class="navbar-inner"> 
		<div class="container">
			<%= link_to "voting app", root_path, id: "logo" %>
				<nav>
					<ul class="nav nav-pills pull-right">
						<li><%= link_to "Home", root_path, class: "active" %></li>
						<li><%= link_to "Help", help_path %></li>
						<% if user_signed_in? %>
							<li><%= link_to "Edit profile", edit_user_registration_path %></li>
							<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to "Sign in", new_user_session_path %></li>
							<li><%= link_to "Sign up", new_user_registration_path %></li>
						<% end %>
					</ul>
				</nav>
		</div>
	<div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<%= render partial: "shared/flash_messages", flash: flash %>

		<div class="container">
			<div>
				<%= yield %>
			</div>
			<%= link_to "Back", :back, class: "btn btn-inverse btn-sm pull-right" %>
			<%= render 'layouts/footer' %>
		</div>
			
	</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
	<div class="alert <%= bootstrap_class_for(type) %> fade in">
		<button class="close" data-dismiss="alert">×</button>
		<%= message %>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About us</h1>
<p>We are a team of one!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact us!</h1>
<p>
Go ahead, send us an email!
Just send us an email!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help Page!</h1>
<p>Need some help?</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<h1>Voting App!</h1>
	<h3>Here you can vote for the best articles!</h3>
</div>
<div id="article_list">
	<%= render partial: 'articles/article_list' %>
</div>
<%= link_to 'New Article', new_article_path, class: 'btn btn-primary', remote: true %>
<div class="modal fade" role="dialog"></div>

app/views/votes/create.js.erb
$('.glyphicon-heart').html('<%= j(render partial: 'articles/_article_list') %>');